### ISSUE TITLE
Bug in changing files to compare

### ISSUE THREAD

**Issue by dwijnand** [sjl/splice.vim#10]
When in compare mode, I'm having trouble switching from comparing One and Result to Two and Result.

With One select I try and switch it with Two, but the result is One and Two instead.

**Comment by errael** [comment]
Hi @dwijnand , @Profpatsch, @vlmarek

I've just released [Splice9](https://github.com/errael/splice9); it's pure `vim9script`, no `python`; it's compatible with the original Splice with additional features, particularly UI. I've addressed some issues against the original Splice (see below) and I'm wondering about this issue.

Think that this issue and #16 and #32 all the same thing?

Feature: #30, #15, https://github.com/errael/splice9/issues/16
